### PR TITLE
Fix logging of migration sql

### PR DESCRIPTION
**Pull request by Connorhd**

### CODE REVIEW

**Comment by nhamal** [comment]
I definitely want this, but i also don't actually understand AR code enough to review it confidently.

Can you post a sample of what it outputs after this change/

**Review by ablackmon — APPROVED** [review]
I'm with Nathan on the "uhhh do what now" 
But will actually approve ;) 

It's actually that it seems weird it ever worked.

**Comment by Connorhd** [comment]
Yeah I couldn't find any documentation for this, but the `log` method takes the SQL then the "name" of the operation, "SCHEMA" is meant for the "SHOW TABLE" type queries rails runs, so isn't right. By testing I worked out that the MySQL adapter passes `nil` here for migrations so I matched that. I think this was probably placeholder code that just never got filled in. I also tested this works manually.

**Comment by Connorhd** [comment]
To be clear the only thing that was broken is the logging, and the `capture_migration_sql` gem hooks into the logger to get the raw sql

**Pull request merged**
